spring:
  datasource:
    url: jdbc:postgresql://192.168.1.99:26257/test?sslmode=disable
    username: root
    password:
model:
  outputPath: ".output"
  tables:
    - name: "accounts"
      count: "100"
      files: 1
      columns:
        - name: "acc_no"
          expression: "randomString(512)"
        - name: "pos_dt"
          constant: "2024-05-13"
        - name: "ent_id"
          expression: "randomBigDecimal(0,9223372036854775807,0)"
        - name: "col_00"
          expression: "randomString(512)"
        - name: "col_01"
          expression: "randomString(512)"
        - name: "col_02"
          expression: "randomString(512)"
        - name: "col_03"
          expression: "randomString(512)"
        - name: "col_04"
          expression: "randomBigDecimal(0,10000000000000000,6)"
        - name: "col_05"
          expression: "randomBigDecimal(0,10000000000000000,6)"
        - name: "col_06"
          expression: "randomString(512)"
        - name: "col_07"
          expression: "randomBigDecimal(0,100000000000000,8)"
        - name: "col_08"
          expression: "randomBigDecimal(0,100000000000000000,3)"
        - name: "col_09"
          expression: "randomBigDecimal(0,10000000000000000,4)"
        - name: "col_10"
          expression: "randomBigDecimal(0,100000000000000000,3)"
        - name: "col_11"
          expression: "randomBigDecimal(0,1000000000000000,5)"
        - name: "col_12"
          expression: "randomBigDecimal(0,1000000000000000,5)"
        - name: "col_13"
          expression: "randomBigDecimal(0,1000000000000000,5)"
        - name: "col_14"
          expression: "randomBigDecimal(0,1000000000000000,5)"
        - name: "col_15"
          expression: "randomBigDecimal(0,100000000000000000,3)"
        - name: "col_16"
          expression: "randomBigDecimal(0,100000000000000000,3)"
        - name: "col_17"
          expression: "randomBigDecimal(0,10000000000000,8)"
        - name: "col_18"
          expression: "randomBigDecimal(0,10000000000000,8)"
        - name: "col_19"
          expression: "randomBigDecimal(0,9223372036854775807,2)"
        - name: "col_20"
          expression: "randomBigDecimal(0,9223372036854775807,2)"
        - name: "col_21"
          expression: "randomBigDecimal(0,9223372036854775807,2)"
        - name: "col_22"
          expression: "randomBigDecimal(0,9223372036854775807,2)"
        - name: "col_23"
          expression: "randomString(512)"
        - name: "col_24"
          expression: "randomString(512)"
        - name: "col_25"
          expression: "randomBigDecimal(0,10000000000000,9)"
        - name: "col_26"
          expression: "randomBigDecimal(0,10000000000000,8)"
        - name: "col_27"
          expression: "randomBigDecimal(0,10000000000000,8)"
        - name: "col_28"
          expression: "randomBigDecimal(0,10000000000000,9)"
        - name: "col_29"
          expression: "randomBigDecimal(0,1000000000000000,5)"
        - name: "col_30"
          expression: "randomBigDecimal(0,1000000000000000,5)"
        - name: "col_31"
          expression: "randomBigDecimal(0,1000000000000000,5)"
        - name: "col_32"
          expression: "randomBigDecimal(0,1000000000000000,5)"
        - name: "col_33"
          expression: "randomBigDecimal(0,1000000000000000,5)"
        - name: "col_34"
          expression: "randomBigDecimal(0,1000000000000000,5)"
        - name: "col_35"
          expression: "randomBigDecimal(0,1000000000000000000,2)"
        - name: "col_36"
          expression: "randomBigDecimal(0,1000000000000000000,2)"
        - name: "col_37"
          expression: "randomBigDecimal(0,1000000000000000,5)"
        - name: "col_38"
          expression: "randomDate()"
        - name: "col_39"
          expression: "randomDate()"
        - name: "col_40"
          expression: "randomDate()"
        - name: "col_41"
          expression: "randomString(512)"
        - name: "col_42"
          expression: "randomBigDecimal(0,1000000000000000,6)"
        - name: "col_43"
          expression: "randomBigDecimal(0,1000000000000000,6)"
        - name: "col_44"
          expression: "randomBigDecimal(0,1000000000000000,6)"
  import:
    options:
      delimiter: ","
      skip: "1"
      allow_quoted_null: "null"
    file: "import.sql"
    prefix: "http://${local-ip}:8090/"
